version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - eventure-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - eventure-net

  eventure:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventure
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_ELASTICSEARCH_CONNECTION_TIMEOUT=5s
      - SPRING_ELASTICSEARCH_SOCKET_TIMEOUT=10s
    networks:
      - eventure-net

networks:
  eventure-net:
    driver: bridge
